### ISSUE TITLE
Duda sobre if

### ISSUE THREAD

**Issue by FrogEmperor** [ahiralesc/ICC003Tests#1]
No tendria que ser if (val2==3)?
o lo que se refiere en el comentario es que lo pongamos manualmente?
https://github.com/ahiralesc/ICC003Tests/blob/e707d9b2bb4ea53fd8b4772cec52857c02e56a13/LinkedList/test/LinkedList_minmax_test.cpp#L45

**Comment by ahiralesc** [comment]
En los codigos de prueba coloque el comentario TODO seguido de un valor o una expresion que debe utilizar en el condicional del codigo. Debes remplazar el codigo del condicional con el del comentario. Por ejemplo,

// Codigo viejo
if ( val1 == 1) // TODO: cambiar el valor a 3

// Codigo nuevo
if ( val1 == 3)
