### ISSUE TITLE
If

### ISSUE THREAD

**Issue by FrogEmperor** [ahiralesc/ICC003Tests#2]
No deberia ser if( min_heap.size() == 9) ya que solo se hace min_heap.pop() una vez?
https://github.com/ahiralesc/ICC003Tests/blob/f48d967238ef388281dedc040b47f86b508b574d/Heap/test/PriorityQueue_size.cpp#L40

**Comment by ahiralesc** [comment]
Ya fueron corregidas todas las pruebas. Gracias por la observacion.
